/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfredx
 */
public class Enrollment extends javax.swing.JFrame {

    /**
     * Creates new form Enrollment
     */
    JavaConnector jc;
    List<courseDetails> courses;
    int [] EnrollmentCounter;
    courseDetails EnrollCandidate;
    MenuObjects MenuObjects;
    public Enrollment(JavaConnector jc, int[] EnrollmentCounter, MenuObjects MenuObjects) {
        initComponents();
        this.jc = jc;
        this.EnrollmentCounter = EnrollmentCounter;
        getAllCourses();
        this.totalNum.setText("There are "+ courses.size()+" available classes in total.");
        this.MenuObjects = MenuObjects;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CoursesTable1 = new javax.swing.JTable();
        totalNum = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(747, 616));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 255));
        jLabel5.setText("Enrollment");

        CoursesTable1.setAutoCreateRowSorter(true);
        CoursesTable1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        CoursesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "UosCode", "Title", "Semester", "Year", "Enrollment", "Max Enrollment", "Instructor Name"
            }
        ));
        CoursesTable1.setRowHeight(30);
        CoursesTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoursesTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CoursesTable1MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(CoursesTable1);

        totalNum.setText("There are 99 classes in total.");

        jButton1.setText("Enroll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(459, 459, 459))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CoursesTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoursesTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CoursesTable1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
            this.EnrollmentCounter[0]--;        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void CoursesTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoursesTable1MousePressed
        int rowIndex = this.CoursesTable1.getSelectedRow();                    // TODO add your handling code here:
         EnrollCandidate= courses.get(rowIndex);
    }//GEN-LAST:event_CoursesTable1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (EnrollCandidate!= null){
            int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Do you want to enroll in "+ EnrollCandidate.UosCode +", "+EnrollCandidate.semester +" " + EnrollCandidate.year+", taught by " + EnrollCandidate.Name+"?", 
                                  "Choose", 
                                  JOptionPane.YES_NO_OPTION); 
            if (selectedOption == JOptionPane.YES_OPTION) {
                try{
                    List<course> failedEnroll = jc.Enroll(EnrollCandidate.UosCode, EnrollCandidate.semester, EnrollCandidate.year);
                    if(failedEnroll.size() != 0){
                        String failedMessage="";
                        for(int i = 0; i< failedEnroll.size();i++) {
                            failedMessage += i+1 +"."+ failedEnroll.get(i).UosCode+"\n";
                        }
                        JOptionPane.showMessageDialog(rootPane, "The following classes need to be done before enrolling in:\n"+failedMessage);
                    }
                } catch(SQLException except) {
                    if (except.getErrorCode() ==0){
                        JOptionPane.showMessageDialog(rootPane, "You are succesfully Enrolled");
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, except.getMessage());   
                    }           
                }
            }
            EnrollCandidate = null;
            getAllCourses(); 
            MenuObjects.Transcript.getTranscript();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void getAllCourses(){
        try{
             int quarterNum = Integer.valueOf(jc.quarter.substring(1));
             quarterNum = (quarterNum +1)%4;
             if (quarterNum == 0) quarterNum =4;
             String nextQuarter = "Q"+quarterNum;
                System.out.println(jc.year +","+jc.quarter +","+ nextQuarter);
                courses = jc.getAllCourses(jc.year, jc.quarter, nextQuarter );
                DefaultTableModel model = (DefaultTableModel) CoursesTable1.getModel();
                int rows = model.getRowCount(); 
                for(int i = rows - 1; i >=0; i--){
                   model.removeRow(i); 
                }
                for (int i = 0; i< courses.size(); i++){
                    courseDetails c= courses.get(i);               
                    Object[] row = {c.UosCode,c.CourseTitle,c.semester,c.year,c.Enrollment,c.MaxEnrollment,c.Name};
                    model.addRow(row);
                } 
                
        } catch(SQLException except) {
            JOptionPane.showMessageDialog(rootPane, except.getMessage());
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CoursesTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel totalNum;
    // End of variables declaration//GEN-END:variables
}
